adopte_un_etudiant/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^', include('profils.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profils/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.home, name= 'home'),
    url(r'^inscription/$', views.inscription),
    url(r'^connexion/$', views.connexion, name = 'connexion'),
    url(r'^deconnexion/$', views.deconnexion, name = 'deconnexion'),
    url(r'^annonces/$',views.list_annonces),
    url(r'^annonce/(?P<numero>\d+$)',views.annonce, name= 'lire_annonce'),
    url(r'^proposer_annonce/$',views.proposer_annonce),
    url(r'^postuler_annonce/(?P<numero>\d+$)',views.postuler_annonce, name = 'postuler_annonce'),
    url(r'^test/?$', views.test, name = 'test'),
    url(r'^profil/?$', views.profil, name = 'profil'),
    url(r'^modifier_profil/?$', views.modifier_profil),
    url(r'^modifier_photo/?$', views.modifier_photo),
    url(r'^supprimer_photo/?$', views.supprimer_photo), 
    url(r'^voir_annonces_perso/(?P<etat>\w+$)', views.voir_annonces_perso),
    url(r'^annonce_perso/(?P<numero>\d+$)',views.annonce_perso, name= 'lire_annonce_perso'),
    url(r'^modifier_annonce/(?P<numero>\d+$)',views.modifier_annonce, name= 'modifier_annonce'),
    url(r'^supprimer_annonce/(?P<numero>\d+$)',views.supprimer_annonce, name= 'supprimer_annonce'),
    url(r'^annuler_annonce/(?P<numero>\d+$)', views.annuler_annonce, name = 'annuler_annonce'),
    url(r'^accepter_annonce/(?P<numero>\d+$)', views.accepter_annonce, name = 'accepter_annonce'),
    url(r'^refuser_annonce/(?P<numero>\d+$)', views.refuser_annonce, name = 'refuser_annonce'),
    url(r'^annonce_effectuee/(?P<numero>\d+$)', views.annonce_effectuee, name = 'annonce_effectuee'),
]

profils/models.py
from django.db import models
from django import forms
from django.contrib.auth.models import User

"""
Les attributs de la classe User sont :
    -username
    -first_name
    -last_name
    -email
    -password
    -is_staff
    -is_active
    -is_superuser
    -last_login
    -date_joined
    -user_permissions
    -groups
"""

class Profil(models.Model):
    user = models.OneToOneField(User)
    age = models.IntegerField()
    photo = models.ImageField(upload_to="photos/")
    is_student = models.BooleanField()
    ecole = models.CharField(null=True, max_length=100)
    description = models.TextField(null=True)
    #"homme" ou "femme"
    sexe = models.CharField(max_length=10)
    
    def __str__(self):
        return self.user.username
        

        
class Annonce (models.Model):
	""" Classe qui va gérer tout ce qui concerne les articles"""
	titre = models.CharField(max_length=200)
	 #boulot = models.CharField(max_length=50)
	annonce = models.TextField(null=False)
	date = models.DateTimeField(auto_now_add=True, auto_now=False, verbose_name = "Date de dépôt")
	prix = models.DecimalField(max_digits=5,decimal_places=2)
	annonceur = models.CharField(max_length=100)
	etudiant = models.CharField(max_length=100, blank=True) # blank permet de rendre ce champs optionnel 
	lieux = models.CharField(max_length=50)
	distance_max = models.IntegerField()
	numero = models.IntegerField()
	#etat ne peux prendre que 3 valeurs : "a_faire", "fait", "en_cours"
	etat = models.CharField(max_length=10)
	postulant = models.CharField(max_length=100, null=True)
	message_postulant = models.TextField(max_length=1000,null=True)

	def __str__(self) :
		return self.titre 
		


class Avis(models.Model):
    posteur = models.CharField(max_length=100)
    receveur = models.CharField(max_length=100)
    note = models.IntegerField()
    commentaire = models.TextField(null=True)
    numero = models.IntegerField()

    def __str__(self) :
        return self.numero

profils/forms.py
from django import forms
"""
BIRTH_YEAR_CHOICES = ('1980', '1981', '1982')
FAVORITE_COLORS_CHOICES = (
    ('blue', 'Blue'),
    ('green', 'Green'),
    ('black', 'Black'),
)

class InscriptionForm(forms.Form):
    birth_year = forms.DateField(widget=forms.SelectDateWidget(years=BIRTH_YEAR_CHOICES))
    favorite_colors = forms.MultipleChoiceField(
        required=False,
        widget=forms.CheckboxSelectMultiple,
        choices=FAVORITE_COLORS_CHOICES,
    )

"""
SEXE_CHOICES = (('homme','Homme'),('femme','Femme'))
NOTE_CHOICES = (('A','A'),('B','B'),('C','C'),('D','D'),('E','E'),('F','F'))

class InscriptionForm(forms.Form):
    pseudo = forms.CharField()
    prenom = forms.CharField()
    nom = forms.CharField()
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)
    age = forms.IntegerField()
    photo = forms.ImageField(required=False)
    description = forms.CharField(required=False,label="Description (facultative)",widget=forms.Textarea)
    is_student = forms.BooleanField(required=False,label = "cochez si vous êtes étudiant")
    école = forms.CharField(required=False,label = "rentrez votre école si vous êtes étudiant")
    sexe = forms.ChoiceField(choices=SEXE_CHOICES)
    charte = forms.BooleanField(label ="J'ai pris connaisance de le charte et je l'accepte")
    
    
    
class ConnexionForm(forms.Form):
    username = forms.CharField(label="Pseudo")
    password = forms.CharField(label="Mot de passe", widget=forms.PasswordInput)
    

class AnnonceForm(forms.Form) :
    titre = forms.CharField(max_length=200)
    #boulot = forms.ModelChoiceField(queryset=('Ménage','Déménagement','Plomberie','Jardinage','Cours','Service d\'aide à la personne','autre...'), empty_label=None)
    annonce = forms.CharField(widget=forms.Textarea, label="Décrivez votre petite annonce")
    prix = forms.DecimalField(max_digits=5,decimal_places=2)
    lieux = forms.CharField(max_length=50)
    distance_max = forms.IntegerField(label="Indiquez la distance maximale en km que vous pouvez faire pour chercher un étudiant. Mettez 0 si vous ne voulez pas aller le chercher")
    
    
class PostulerAnnonceForm(forms.Form):
    Commentaires = forms.CharField(label = 'expliquez pourquoi le personne qui a postée cette annonce devrait vous prendre (facultatif)', required = False )
    
class ModifierProfilForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput, label = "Mot de passe actuel")
    pseudo = forms.CharField(label = "Nouveau pseudo")
    new_password = forms.CharField(widget=forms.PasswordInput, label="Rentrez votre nouveau mot de passe")
    description = forms.CharField(required=False,label="Nouvelle description (facultative)")
    is_student = forms.BooleanField(required=False,label = "cochez si vous êtes étudiant")
    école = forms.CharField(required=False,label = "rentrez votre école si vous êtes étudiant")
    
class ModifierPhotoForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput)
    photo = forms.ImageField(required=False)
    #password = forms.CharField(widget=forms.PasswordInput, label = "Mot de passe actuel")    
    #photo = forms.ImageField(label = "Nouvelle photo")
    


class ModifierAnnonceForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput, label = "Mot de passe actuel")
    titre = forms.CharField(max_length=200)
    annonce = forms.CharField(widget=forms.Textarea, label="Décrivez votre petite annonce")
    prix = forms.DecimalField(max_digits=5,decimal_places=2)
    lieux = forms.CharField(max_length=50)
    distance_max = forms.IntegerField(label="Indiquez la distance maximale en km que vous pouvez faire pour chercher un étudiant. Mettez 0 si vous ne voulez pas aller le chercher")
    
class DemanderPasswordForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput, label = "Mot de passe actuel")
    
class CommentaireForm(forms.Form):
    Note = forms.ChoiceField(choices=NOTE_CHOICES)
    Commentaire = forms.CharField(required=False)
    
    












    
    

profils/templates/profils/accepter_annonce.html
<!DOCTYPE html>
<html lang="fr">


<head>
{% load static %}

    <link rel="stylesheet" href="{% static 'style.css' %}" />
	<title>Accepter annonce</title>
</head>>

<body>

<div class="background">
<h1>Accepter cette annonce</h1>


{% if wrong_password %}

    <p>Votre mot de passe est incorrect!</p>

{% endif %}

   

<p>

    <form method="post" enctype="multipart/form-data" action="./{{ numero }}">

       {% csrf_token %}

       {{ form.as_p }}

       <input type="submit"/>

    </form>

</p>

</div>
</body>
</html>

profils/templates/profils/annonce_non_existante.html
<h2> <span class="small"> L'annonce que vous avez essayé de consulter n'existe pas </span> </h2>

profils/templates/profils/annonce_perso.html
<!DOCTYPE html>
<html lang="fr">
<head>
{% load static %}

    <link rel="stylesheet" href="{% static 'style.css' %}" />
	<title> annonce n° {{annonce.numero}}</title>
</head>


<body>
<div class="background">

<h1> Voici l'annonce proposée par {{annonce.annonceur}} le {{annonce.date|date:"DATE_FORMAT"}} </h1>
<img src="{{profil_annonceur.photo.url }}" width="10%" heigth="10%"/>


<p> A {{ annonce.lieux}} </p>

<p> Payé {{annonce.prix}} €</p>



{% if Bool %}
	
	<p> Possibilité de trajet jusuqu'à {{annonce.distance_max}} </p>

{% endif %}

<p>	Description : {{annonce.annonce}} </p>

{% if annonce.postulant == None %}

<a href="{% url "modifier_annonce" numero%}">Modifiez cette annonce</a></br>
<a href="{% url "supprimer_annonce" numero%}">Supprimez cette annonce</a>

{% else %}
    {% if annonce.postulant == request.user.username %}
        {% if annonce.etudiant == '' %}
            <p> Vous avez postulé pour cette annonce! </p>
            <p> Message : {{ annonce.message_postulant}} </p>
            <a href="{% url "annuler_annonce" numero%}">Annuler votre demande de réservation</a></br>
        {% elif annonce.etat == "en_cours" %}
            <p> Votre demande a été acceptée. Il vous faut maintenant effectuer cette annonce! </p>
            <p> Contactez {{annonce.annonceur}} : {{user_annonceur.email}} </p>
            <a href="{% url "annuler_annonce" numero%}">Annuler votre demande de réservation</a></br>
        {% else %}
            <p>Vous avez bien effectué cette annonce</p>
            <a href="{% url "donner_avis" annonce.annonceur annonce.etudiant %}">Donnez lui un avis</a></br>
        {% endif %}
    {% elif annonce.etudiant == '' %}
        
        <p> {{ annonce.postulant}} a postulé pour cette annonce! </p>
        <p> Message : {{ annonce.message_postulant}} </p>
        <a href="{% url "accepter_annonce" numero%}">Accepter</a></br>
        <a href="{% url "refuser_annonce" numero%}">Refuser</a></br>
    {% elif annonce.etat == "en_cours" %}
        <p> Vous avez accepter que {{ annonce.postulant}} effectue cette annonce!</br>Contactez le : {{user_etudiant.email}}</p>
        <p> Message : {{ annonce.message_postulant}} </p>
        <a href="{% url "annuler_annonce" numero%}">Annuler</a></br>
        <a href="{% url "annonce_effectuee" numero%}">L'annonce a bien été effectuée</a></br>
    {% else %}
        <p> {{ annonce.postulant}} a bien effectué cette annonce! </p>
    {% endif %}
{% endif %}



</div>
</body>
</html>

profils/templates/profils/inscription.html
<!DOCTYPE html>
<html lang="fr">


<head>
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}" >
    <link rel="stylesheet" href="{% static 'css/specificStyle.css' %}" >
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
    <script src="{% static 'js/jquery-3.1.1.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
	<title>Inscription</title>
</head>

<body>
	<div class="container-fluid" id="container-etudiant">

      <div class="row">
        <div class="col-md-12">

          <nav class="navbar navbar-default" id="etudiant-navbar">
            <div class="container-fluid">
              <div class="navbar-header">
                <a class="navbar-brand" href="#">
                  <img src="{% static 'img/logo.png' %}" alt="mon image" id="brandimage">
                </a>
                <a class="navbar-brand" href="/" id="etudiant-title">Adopte un étudiant</a>
              </div>

                  <!-- Collect the nav links, forms, and other content for toggling -->
              <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav" id="nav-list">
                  <li>
                    <a href="/"><span class="glyphicon glyphicon-home"></span>Accueil</a>
                  </li>
                  <li>
                    <a href="/annonces"><span class="glyphicon glyphicon-tags"></span>Voir les annonces</a>
                  </li>
                  <li>
                    <a href="/connexion"><span class="glyphicon glyphicon-log-out"></span>Connexion</a>
                  </li>
                </ul>
              </div><!-- /.navbar-collapse -->

            </div>
          </nav>

          </div><!-- col12 -->
        </div><!-- row -->

				<div class="row">
					<div class="col-md-3"></div>
					<div class="col-md-6">
						<form method="post" enctype="multipart/form-data" action=".">
							<fieldset>

								  <div class="form-group">
								    <label for="id_pseudo">Choisissez un pseudo :</label>
		       					<input id="id_pseudo" name="pseudo" class="form-control" type="text" required="required">
								  </div>

								  <div class="form-group">
								    <label for="id_password">Mot de passe</label>
								    <input type="password" name="password" class="form-control" id="id_password" placeholder="Votre mot de passe vraiment sécurisé" required="required">
								  </div>

								  <div class="form-group">
								    <label for="id_prenom">Prénom :</label>
								    <input type="text" name="prenom" class="form-control" id="id_prenom" placeholder="Votre premier prénom" required="required">
								  </div>

								  <div class="form-group">
	       						<label for="id_nom">Nom :</label>
	       						<input class="form-control" id="id_nom" name="nom" type="text" placeholder="Votre nom" required>
	       					</div> 

	       					<div class="form-group">
	       						<label for="id_sexe" >Sexe </label>
				       			<select id="id_sexe" name="sexe" required>
										<option value="homme" selected="selected">Homme</option>
										<option value="femme">Femme</option>
										</select>
				       		</div>

				       		<div class="form-group">
				       			<label for="id_email" >Email :</label>
				       			<input class="form-control" id="id_email" name="email" type="email" placeholder="adopte@email.com" required />
				       		</div>

				       		<div class="form-group">
				       			<label for="id_password">Password :</label>
				       			<input class="form-control" id="id_password" name="password" type="password" placeholder="Votre mot de passe sécurisé" required />
				       		</div>

				       		<div class="form-group">
				       			<label for="id_age" >Age :</label>
				       			<input class="form-control" id="id_age" name="age" type="number" required />
				       		</div>

									<div class="form-group">
				       			<label for="id_photo" >Photo :</label>
				       			<input id="id_photo" name="photo" type="file" /></td></tr>
				       		</div>	

				       		<div class="form-group">
				       			<label for="id_description">Description (facultative) :</label>
				       			<textarea class="form-control" cols="20" id="id_description" name="description" rows="1" style="resize: auto"></textarea>
				       		</div>       	

									<div class="checkbox">
					       		<label>
					       			<input id="id_is_student" name="is_student" type="checkbox" />Cochez si vous êtes étudiant
					       		</label>
					       	</div>

									<div class="form-group">
				       			<label for="id_école">Rentrez votre école si vous êtes étudiant :</label>
				       			<input class="form-control" id="id_école" name="école" type="text" />
				       		</div>
									
					       	<br>
					       	<div class="form-group">
					       		<textarea id="autre" class="form-control" cols="50" id="id_description" name="autre" rows="10" readonly>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
					       		</textarea>
					       	</div>

					       	<div class="checkbox">
					       		<label>
					       			<input id="id_charte" name="charte" type="checkbox" /><strong>J'ai pris connaissance de la charte et je l'accepte</strong>
					       		</label>
					       	</div>

								  <button type="submit" class="btn btn-primary">S'inscrire</button>
							</fieldset>
						</form>
					</div>
					<div class="col-md-3"></div>
				</div>

				<div class="row">
	        <div class="col-md-12">
	          <footer>
	            <div class="panel panel-default">
	              <div class="panel-body">
	                <strong>Écrit avec passion par PL, Quentin et Thomas</strong>
	              </div>
	              <div class="panel-footer lobster">&copy; Adopte un étudiant</div>
	            </div>
	          </footer>
	        </div>
      	</div>

    </div><!-- container fluid -->

</body>
</html>

<!--
<h1>Inscription</h1>


{% if wrong_email %}

    <p>Cet adresse email a déjà été utilisée.</p>

{% endif %}

{% if wrong_username %}

    <p>Ce pseudo a déjà été utilisé.</p>

{% endif %}

{% if wrong_ecole %}

    <p>Vous avez oublié de spécifier votre école.</p>

{% endif %}

<p>

    <form method="post" enctype="multipart/form-data" action=".">

       {% csrf_token %}

      
       {{ form.as_p }}

       <input type="submit"/>

    </form>

</p>


-->

profils/templates/profils/proposer_annonce.html
<!DOCTYPE html>
<html lang="fr">

<head>
  	<meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      {% load static %}

      <link rel="stylesheet" href="{% static 'css/specificStyle.css' %}" >
      <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
      <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
      <script src="{% static 'js/bootstrap.min.js' %}"></script>
      <link rel="icon" type="image/png" href="{% static 'img/logo.png' %}" />
      <title>{% block title %}Annonces{% endblock %}</title>
      <!-- 
      var screen=document.getElementById('niark');
      var screenWidth = parseFloat(window.getComputedStyle(screen).width),
      screenHeight = parseFloat(window.getComputedStyle(screen).height);
      -->
</head>



<body>
	<div class="container-fluid" id="container-etudiant">

      <div class="row">
        <div class="col-md-12">

        	  <nav class="navbar navbar-default" id="etudiant-navbar">
            <div class="container-fluid">
              <div class="navbar-header">
                <a class="navbar-brand" href="#">
                  <img src="{% static 'img/logo.png' %}" alt="mon image" id="brandimage">
                </a>
                <a class="navbar-brand" href="/" id="etudiant-title">Adopte un étudiant</a>
              </div>

                  <!-- Collect the nav links, forms, and other content for toggling -->
              <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav" id="nav-list">
                  <li>
                    <a href="/"><span class="glyphicon glyphicon-home"></span>Accueil</a>
                  </li>
                  <li>
                    <a href="/annonces"><span class="glyphicon glyphicon-tags"></span>Voir les annonces</a>
                  </li>
                  {% if not request.user.is_authenticated %}
                  <li>
                    <a href="/inscription" ><span class="glyphicon glyphicon-pencil"></span>Inscription</a>
                  </li>
                  <li>
                    <a href="/connexion"><span class="glyphicon glyphicon-log-out"></span>Connexion</a>
                  </li>
                  {% else %}
                  <li>
                    <a href="/proposer_annonce"><span class="glyphicon glyphicon-cloud-upload"></span>Proposer une annonce</a>
                  </li>
                  <li>
                    <a href="/voir_annonces_perso/a_faire"><span class="glyphicon glyphicon-eye-open"></span>Voir vos annonces</a>
                  </li>
                  <li>
                    <a href="/profil"><span class="glyphicon glyphicon-user"></span>Profil</a>
                  </li>
                  <li>
                  	<a href="/deconnexion"><span class="glyphicon glyphicon-log-out"></span>Deconnexion</a>
                  </li>
                  {% endif %}

                </ul>
              </div><!-- /.navbar-collapse -->

            </div>
          </nav>

          </div><!-- col12 -->
        </div><!-- row -->

	
		<div class="row" >
			<div class="col-md-5 col-md-offset-3" >
				<h1 class="lobster">Nouvelle Annonce proposée par {{ request.user.username }}</h1>
				<hr>
				<div >
					<form class="form-horizontal" method="post" enctype="multipart/form-data" action=".">
					<fieldset>
						{% csrf_token %}
						<div class="form-group">
							<label for="id_titre">Titre </label>
							<input class="form-control" id="id_titre" maxlength="200" name="titre" type="text" placeholder="Jardinage" required />
						</div>

						<div class="form-group">
								<label for="id_annonce">Décrivez votre petite annonce </label>
								<textarea  class="form-control" cols="20" id="id_annonce" name="annonce" rows="2" required></textarea>
						</div>

						<div class="form-group">
								<label for="id_prix">Prix </label>
								<input class="form-control" id="id_prix" name="prix" step="0.01" type="number" required />
						</div>

						<div class="form-group">
								<label for="id_lieux">Lieux </label>
								<input class="form-control" id="id_lieux" maxlength="50" name="lieux" type="text" required /></td></tr>
						</div>

						<div class="form-group">
								<label for="id_distance_max">
								Indiquez la distance maximale en km que vous pouvez faire pour chercher un étudiant. Mettez 0 si vous ne voulez pas aller le chercher</label>
								<br/>
								<input class="form-control" id="id_distance_max" name="distance_max" type="number" required />
						</div>

						<div >
				       		<button class="btn btn-primary" type="submit"> Poster l'annonce </button> 
				   		</div>

						
					</fieldset>
					</form>
				</div>
			</div>
		</div>
	</div>




</body>
</html>

profils/templates/profils/test.html
<!DOCTYPE html>
<html lang="fr">


<head>
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}" >
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
	<title>Inscription</title>
</head>

<body>

<nav class="navbar navbar-inverse navbar-fixed-top" style= "background-color: #1976D2; margin-bottom: 5%">
  <div class="container-fluid" >  
    <div id="navbar" style="display: inline-block;">
        <img src="{% static 'img/logo.png' %}" alt="mon image" width="10%" height="10%">
    </div>
    <div class="navbar-header" >
      <a class="navbar-brand" href="/" style="color :#FFFFFF">Adopte un etudiant</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse" >
      <ul class="nav navbar-nav" style="float:right; margin : -4% 0 0 0" >
        <li class="active" ><a href="/" style="background-color: #1976D2">Accueil</a></li>
        <li><a href="/annonces" style="color:#FFFFFF">Voir les annonces</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<div class="container-fluid">
	<div class="row" style="text-align:center;background-color: #2196F3">
		<div class="col-lg-8 col-lg-offset-2" style="margin-top: 3%">
			<h1>Inscrivez-vous et rejoignez notre communauté !</h1>
		</div>
	</div>
	
	<fieldset>

		<div class="row" style="background-color: #BBD
		<!--conditions -->
		{% if wrong_email %}
	    	<p>Cet adresse email a déjà été utilisée.</p>
		{% endif %}

		{% if wrong_username %}
	    	<p>Ce pseudo a déjà été utilisé.</p>
		{% endif %}
		<form class="form-horizontal" method="post" enctype="multipart/form-data" action="." >
			{% csrf_token %}
		
			<br>
	       	<div class ="row">
	       		<div class="form-group">
	       			<label for="id_pseudo" class="col-lg-1 col-lg-offset-4" style="text-align: center">Pseudo :</label>
	       			<input id="id_pseudo" name="pseudo" type="text" size="auto" required />
	       		</div>
	       	</div>

	       	<div class ="row">
	       		<div class="form-group">
	       			<label for="id_prenom" class="col-lg-1 col-lg-offset-4" style="text-align:center">Prenom :</label>
	       			<input id="id_prenom" name="prenom" type="text" required />
	       		</div>
	       	</div>

	       	<div class ="row">
	 			<div class="form-group">
	       			<label for="id_nom" class="col-lg-1 col-lg-offset-4" style="text-align: center">Nom :</label>
	       			<input id="id_nom" name="nom" type="text" required />
	       		</div>
	        </div>

	       	<div class ="row">
	       		<div class="form-group">
	       			<label for="id_email" class="col-lg-1 col-lg-offset-4" style="text-align: center">Email :</label>
	       			<input id="id_email" name="email" type="email" required />
	       		</div>
	       	</div>

	       	<div class ="row">
	       		<div class="form-group">
	       			<label for="id_password" class="col-lg-1 col-lg-offset-4" style="text-align: center">Password :</label>
	       			<input id="id_password" name="password" type="password" required />
	       		</div>
	       	</div>

	       	<div class ="row">
	       		<div class="form-group">
	       			<label for="id_age" class="col-lg-1 col-lg-offset-4" style="text-align: center">Age :</label>
	       			<input id="id_age" name="age" type="number" required />
	       		</div>
	       	</div>

	       	<div class ="row">
	       		<div class="form-group">
	       			<label for="id_photo" class="col-lg-1 col-lg-offset-4" style="text-align: center">Photo :</label>
	       			<input id="id_photo" name="photo" type="file" /></td></tr>
	       		</div>
	       	</div>

	       	<div class ="row">
	       		<div class="form-group">
	       			<label for="id_description" class="col-lg-2 col-lg-offset-3" style="text-align: center">Description (facultative) :</label>
	       			<textarea cols="20" id="id_description" name="description" rows="1" style="resize: auto"></textarea>
	       		</div>
	       	</div>
	       			
	       	<div class ="row">
	       		<div class="form-group">
	       			<label for="id_is_student" class="col-lg-3 col-lg-offset-3" style="text-align: center">Cochez si vous êtes étudiant :</label>
	       			<input id="id_is_student" name="is_student" type="checkbox" />
	       		</div>
	       	</div>

	       	<div class ="row">
	       		<div class="form-group">
	       			<label for="id_école" class="col-lg-3 col-lg-offset-2" style="text-align: center">Rentrez votre école si vous êtes étudiant :</label>
	       			<input id="id_école" name="école" type="text" />
	       		</div>
	       	</div>
			
			
		</form>
		</div> 	

	</fieldset>
</div>
</body>
</html>